#ifndef TESTS_H
#define TESTS_H


/**
 * Number of random tests for every quantity of quadratic equation roots from 0 to 2
 */
#define Num_Tests 10000000


/**
 * \struct TestCase
 * 
 * \brief Parameters for testing quadratic equation
 * 
 * \note x1ref, x2ref MUST BE sorted
 */
struct TestCase{
    double a, b, c;
    enum QuantOfRoots nRootsref; /**<reference number of roots */
    double x1ref = NAN;/**<reference root */
    double x2ref = NAN /**<reference root */;
};


/** 
 * \brief Prints all information about struct TestCase
 * 
 * \param[in] test an element of struct TestCase
*/
void Print_TestCase(TestCase test);


/**
 * \brief Launches one test
 * 
 * \param[in, out] tests_counter the running total number of tests
 * \param[in] test contains a set of reference values
 * \param[in, out] counter_ok_tests number of passed tests
 */
void Run_One_Test(int* tests_counter, TestCase test, int* counter_ok_tests);


/**
 * \brief Run tests for quadratic solver
 * 
 * Runs both manual tests and random tests for every number of roots (0 - 2)
 */
void Run_All_Tests(void);


/**
 * \brief Prints all information about the test if it was failed
 * 
 * Firstly it prints coeffs of equation, the expected number of the roots and the expected roots themselves.
 * Secondly it prints number of roots and roots that was returned by Solver.
 * 
 * \param[in] tests_counter the running total number of tests
 * \param[in] test ...
 * \param[in] x1 the value of the first root that was returned by Solver
 * \param[in] x2 the value of second root that was returned by Solver
 * \param[in] nRoots the value of number of the roots that was returned by Solver
 */
void Write_Test_Failed(int tests_counter, TestCase test, double x1, double x2, QuantOfRoots nRoots);


/**
 * \brief Output of the correct test
 * 
 * Print that test was completely passed
 * 
 * \param[in] tests_counter the running total number of tests
 */
void Write_Test_OK(int tests_counter);


/**
 * \brief Generates random number of type double in the specified range
 * 
 * The sid of random number generation is in function Run_All_Tests (srand(...))
 * 
 * \param[in] min the minimal number that function can return
 * \param[in] max the maximal number that function can return
 * 
 * \return double number in specified range
 */
double Get_Rand(double min, double max);


/**
 * \brief Checks if the given number is the root of the quadratic equation with given coefficients
 * 
 * \param[in] a the coefficient of quadratic equation for x^2
 * \param[in] b the coefficient of quadratic equation for x
 * \param[in] c the free coefficient of quadratic equation
 * \param[in] x the number to check
 * 
 * \return 1 if the number is the root of the quadratic equation else 0
 */
int Check_Root(double a, double b, double c, double x);


/**
 * \brief Run random tests with 0, 1, 2, roots
 * 
 * 0 roots tests are generated by adding to the perfect square a positive number multiplied with a\n
 * #a * (x - x1)^2 + pos_num * a = a * x^2 + (-2 * a * x1) * x + c\n
 * #a = a, b = -2 * a * x1, c = (-2 * a * x1)\n
 * 1 root tests are generated by ganerating perfect square\n
 * #a * (x - x1)^2 = a * x^2 + (-2 * a * x * x1) * x + (a * x1^2)\n
 * #a = a, b = -2 * a * x * x1, c = a * x1^2\n
 * 2 roots tests are generated by subtracting form the perfect square a positive number multiplied with a\n
 * #(a * (x - x1)^2 - pos_num * a = a * x^2 + (-2 * a * x1) * x + a * (x1^2 - pos_num))\n
 * #a = a, b = -2 * a * x1, c = a * (x1^2 - pos_num)\n
 * Obtained coefficients a, b, c are used for Run_One_Test(...)
 * 
 * \param[in] tests_counter the running total number of tests
 * \param[in] counter_ok_tests the number of passed tests
 * \param[in] nRoots the number of roots
 */
void Run_Random_Tests(int* tests_counter, int* counter_ok_tests, enum QuantOfRoots nRoots);


/**
 * \brief Sort po vozrastaniyu two given double numbers
 */
void Sort_Nums(double* a, double* b);

/*TODO: check when a or b is NAN or INF*/


#endif